### ISSUE TITLE
Importer les talks de l'ancien site

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/new-website#7]
L'ancien site des CaenCamp utilisait aussi des articles écrits avec la syntaxe markdown (site propulsé par Jekyll). 
Il s'agit d'importer les fichiers .md de l'ancien site au nouveau.

**Comment by alexisjanvier** [comment]
Voila le format choisi pour les [*front matter*](https://middlemanapp.com/basics/frontmatter/) (genre de metadata pour les fichiers `.md`) des talks : 
```yaml
---
title: "CaenCamp #XX: The title"
slug: "edition-xx-the-title"
date: "YYYY-MM-DD"
description: "A short description display on list view and talk resume"
tags:
    - foo
    - bar
author: author-name-slugified
place: place-name-slugify
---
```
